import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { Toaster } from "@/components/ui/sonner";
import Head from "next/head";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "Doctor App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/icon.png" type="image/png" sizes="32x32" />
      </Head>
      <body className={roboto.className}>
        <div className="md:px-20">
          <Header />
        </div>
        <div
          className="mx-auto max-w-screen-xl px-4 py-8 sm:px-6 sm:py-12 lg:px-8 lg:py-16"
          style={{ minHeight: "calc(100vh - 80px)" }}
        >
          {children}
        </div>
        <Toaster />
        <Footer />
      </body>
    </html>
  );
}
